Update ld16

diff --git a/ld16 b/ld16
--- a/ld16
+++ b/ld16
@@ -4,6 +4,15 @@ CCLD=${CCLD-gcc}
 CCLDFLAGS=${CCLDFLAGS--nostdlib -m16 -O3 -Ttext 0x0100 -Wl,--oformat=binary}
 LIBS=${LIBS--L. -lc -lm}
 
+for file in ${@};
+do
+	ext=${file#.*}
+	if [ -f "${file}"] && ["${ext}" != "o" ];
+	then
+		echo "${0}: error: unrecognized extension ${ext}." 1>&2
+	fi
+done
+
 ${CCLD} ${CCLDFLAGS} ${@} ${LIBS}
 
 exit ${?}
