Update ld16

diff --git a/ld16 b/ld16
--- a/ld16
+++ b/ld16
@@ -6,7 +6,7 @@ LIBS=${LIBS--L. -lc -lm}
 
 for file in ${@};
 do
-	ext=${file##*.}
+	ext=${file#*.}
 	case $ext in
 	C) ;;&
 	c) ;;&
@@ -14,7 +14,7 @@ do
 	cc) ;;&
 	cpp) ;;&
 	S) ;;&
-	s) echo "${0}: error: unrecognized extension ${ext}." 1>&2; exit 1;;
+	s) echo "${0}: error: unrecognized extension .${ext}." 1>&2; exit 1;;
 	esac
 done
 
