Update ld16

diff --git a/ld16 b/ld16
--- a/ld16
+++ b/ld16
@@ -6,11 +6,16 @@ LIBS=${LIBS--L. -lc -lm}
 
 for file in ${@};
 do
-	ext=${file#.*}
-	if [ "${ext}" = "c" -o "${ext}" = "s" ];
-	then
-		echo "${0}: error: unrecognized extension ${ext}." 1>&2
-	fi
+	ext=${file#*.}
+	case $ext in
+	C);;
+	c);;
+	c++);;
+	cc);;
+	cpp);;
+	S);;
+	s) echo "${0}: error: unrecognized extension ${ext}." 1>&2; break;;
+	esac
 done
 
 ${CCLD} ${CCLDFLAGS} ${@} ${LIBS}
